### ISSUE TITLE
create givbacks calculation scripts for retroactive GIVbacks

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/givback-calculation#5]
As per - https://forum.giveth.io/t/retroactive-givbacks/412

We'll need to create calculate givbacks scripts for the three entities outlined in the retroactive GIVbacks initiative. 

> Donations to Giveth get 100% GIVbacks (givFactor 1) (Donations to https://trace.giveth.io/campaign/giveth-dapp-development and https://giveth.io/project/the-giveth-community-of-makers )
> Donations to Verified projects get 75% GIVbacks (Normal eligible donations - we'll have to remove donations to Giveth on IO and TRACE since they are added into the above category)
> Donations to Listed (non-verified) projects get 10% GIVbacks  (givFactor .1)

Does this make sense? 

If you want more context you can check out 
https://docs.google.com/spreadsheets/d/1iJvE5QCd4wXXd-_2tr4x8H0zgqDGMN0yVMub72EPn48/edit?usp=sharing 
under the Retroactive GIVbacks sheets

**Comment by divine-comedian** [comment]
We'll probably need to make two (maybe three) modified scripts 

1. givbacks-calculation that pulls from non-eligible donations to listed only projects
2. givbacks-calculation that selects only donations to giveth on IO and TRACE
3. givbacks calculation that selects eligible donations MINUS donations to IO and TRACE?

Maybe the 2nd or 3rd scripts can be added as a drop down toggle onto the regular givbacks calculation and/or eligible donations script - whatever makes the most sense.

i.e `givethDonations?` -> `only / exclude / normal`

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
 Can you give me link of giveth project in both giveth.io and trace.giveth.io ?

**Comment by divine-comedian** [comment]
> @divine-comedian Can you give me link of giveth project in both giveth.io and trace.giveth.io ?

## Giveth.io
https://giveth.io/project/the-giveth-community-of-makers
eth address - 0x4d9339dd97db55e3b9bcbe65de39ff9c04d1c2cd 
Trace Campaign Id - 5f504e7bfb3dbe37aee4e050 (not sure if this is useful)

## Giveth TRACE 
https://trace.giveth.io/campaign/giveth-dapp-development

**Comment by mohammadranjbarz** [comment]
@divine-comedian  Please check to see wether below endpoint meets your needs or not
https://givback.develop.giveth.io/api-docs/#/default/get_calculate_givback_retroactive


* If you set **yes** for `toGiveth` you would get donations to giveth projects, otherwise you would get donations to other projects
* I think you are familiar with  eligible and justCountListed from previous endpoints
<img width="1412" alt="Screen Shot 1401-01-17 at 22 14 07" src="https://user-images.githubusercontent.com/9850545/162036064-b9144195-2467-4a31-897c-cde41568eea3.png">

**PS** After you did your calculation please tell me to delete this endpoint ( just to not make the project big)

**Comment by divine-comedian** [comment]
currently testing scripts inside this madness 
https://docs.google.com/spreadsheets/d/1Tjr93kb_-fEI5g9ZxGh-ZaWPyaRummnCZZ01aozL_Ow/edit?usp=sharing
